# Spring Core
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password:

## Doma2 Reference URL <https://github.com/domaframework/doma-spring-boot>
#doma:
#  dialect: mysql
#  sql-file-repository: no_cache